# Generated by Django 2.2.5 on 2020-03-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('tipo_menu', models.CharField(choices=[('PADRE', 'padre'), ('HIJO', 'hijo')], max_length=45)),
                ('estado', models.CharField(choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], max_length=50)),
                ('orden', models.IntegerField()),
                ('url', models.CharField(default='#', max_length=60)),
                ('menu_padre', models.ForeignKey(blank=True, db_column='menu_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'db_table': 'menu',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True)),
                ('foto', models.ImageField(default='default/default_avatar.png', upload_to='usuarios_avatar')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': ('Personas',),
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol_nombre', models.CharField(choices=[('PROFESOR', 'Profesor'), ('ADMINISTRADOR', 'Administrador'), ('ALUMNO', 'Alumno'), ('EMPLEADO ADMINITRATIVO', 'Empleado administrativo')], max_length=45)),
                ('rol_estado', models.CharField(choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], max_length=45)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': ('Roles',),
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('correo', models.EmailField(blank=True, default='example@gmail.com', max_length=80, null=True)),
                ('clave', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='seguridad.Personas', unique=True)),
                ('rol_usuario', models.ForeignKey(db_column='rol_usuario', on_delete=django.db.models.deletion.CASCADE, to='seguridad.Roles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': ('Usuarios',),
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True)),
                ('menu', models.ManyToManyField(db_table='permiso_menu', related_name='fk_menu', to='seguridad.Menu')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='fk_rol', to='seguridad.Roles', unique=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': ('Permisos',),
                'db_table': 'permisos',
            },
        ),
    ]
