# Generated by Django 2.2.5 on 2020-03-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True)),
            ],
            options={
                'verbose_name': ('Examen',),
                'verbose_name_plural': ('Examenes',),
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45, unique=True)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True)),
            ],
            options={
                'verbose_name': ('Materia',),
                'verbose_name_plural': ('Materias',),
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('respuesta', models.CharField(choices=[('CORRECTA', 'Correcta'), ('INCORRECTA', 'Incorrecta')], max_length=45)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True)),
            ],
            options={
                'verbose_name': ('Opcion',),
                'verbose_name_plural': ('Opciones',),
                'db_table': 'opciones',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(max_length=200)),
                ('anexo', models.TextField(blank=True, default='No agregar anexo', null=True)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True)),
                ('examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_del_examen', to='evaluacion.Examen')),
                ('opciones', models.ManyToManyField(blank=True, db_table='pregunta_opciones', null=True, related_name='fk_opciones_preguntas', to='evaluacion.Opciones')),
            ],
            options={
                'verbose_name': ('Pregunta',),
                'verbose_name_plural': ('Preguntas',),
                'db_table': 'preguntas',
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='id_materia',
            field=models.ForeignKey(db_column='materia', on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Materia'),
        ),
    ]
