# Generated by Django 2.2.5 on 2020-03-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Usuario'),
            preserve_default=False,
        ),
    ]
