# Generated by Django 2.2.5 on 2020-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_auto_20200326_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
