# Generated by Django 2.2.5 on 2020-03-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_examen_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='anexo',
        ),
    ]
